### ISSUE TITLE
too small "segment bytes" in NZB gives traceback and failed download

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabyenc#14]
too small "segment bytes" in NZB gives traceback and failed download

NZB here https://github.com/sanderjo/NZBs/blob/master/test-too-small-segment-bytes-reftestnzb.nzb

Related to https://github.com/sabnzbd/sabyenc/issues/13

So ... "don't believe the segment bytes!" 

```
2019-06-21 08:25:19,026::INFO::[assembler:319] Error during inspection of RAR-file /home/sander/Downloads/incomplete/test-too-small-segment-bytes-reftestnzb/mytestpost.part05.rar
2019-06-21 08:25:19,027::DEBUG::[assembler:320] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sab2/sabnzbd/assembler.py", line 247, in check_encrypted_and_unwanted_files
    zf = rarfile.RarFile(filepath, all_names=True)
  File "/home/sander/git/sab2/sabnzbd/utils/rarfile.py", line 667, in __init__
    self._parse()
  File "/home/sander/git/sab2/sabnzbd/utils/rarfile.py", line 867, in _parse
    self._file_parser.parse()
  File "/home/sander/git/sab2/sabnzbd/utils/rarfile.py", line 978, in parse
    self._parse_real()
  File "/home/sander/git/sab2/sabnzbd/utils/rarfile.py", line 1002, in _parse_real
    h = self._parse_header(fd)
  File "/home/sander/git/sab2/sabnzbd/utils/rarfile.py", line 1084, in _parse_header
    return self._parse_block_header(fd)
  File "/home/sander/git/sab2/sabnzbd/utils/rarfile.py", line 1619, in _parse_block_header
    header_crc, pos = load_le32(start_bytes, 0)
  File "/home/sander/git/sab2/sabnzbd/utils/rarfile.py", line 2576, in load_le32
    raise BadRarFile('cannot load le32')
BadRarFile: cannot load le32
2019-06-21 08:25:19,028::DEBUG::[misc:1211] [sabnzbd.remove_data] Deleting file /home/sander/Downloads/incomplete/test-too-small-segment-bytes-reftestnzb/__ADMIN__/SABnzbd_nzo_uhaLKI
```

**Comment by sanderjo** [comment]
Workaround, works for both bugs:

```
    def decode(self, article, data, raw_data):
        # Do we have SABYenc? Let it do all the work
        if sabnzbd.decoder.SABYENC_ENABLED:
            mytotal = 0
            for myi in raw_data: 
                mytotal += len(myi)
            logging.debug("SJ: length of raw_data (calculated): %d", mytotal )
            logging.debug("SJ: article.bytes: %s", article.bytes)
            #logging.debug("SJ: raw_data: %s", raw_data )

            '''
            estimatedbytes = article.bytes
            if estimatedbytes < 1 or estimatedbytes > 11222333 :
                logging.warning("SJ: value of segment bytes aka articles.bytes is strange: %s. So resetting value", estimatedbytes)
            '''
            estimatedbytes = int(mytotal * 1.20)
```

**Comment by Safihre** [comment]
This is a known risk. We have the code to calculate the "real" size of what we got in `sabyenc`: https://github.com/sabnzbd/sabyenc/blob/sabyenc-python2/src/sabyenc.c#L565-L568
But this is too CPU-expensive to do for every article.

If we get a botched NZB, those articles will just fail since it's a bad NZB.

**Comment by sanderjo** [comment]
Ah, I see https://github.com/sabnzbd/sabyenc/blob/master/src/sabyenc3.c#L356-L358 at least protects against writing beyond the malloc-ed space:

```
            // Saftey check
            if(decoded_bytes == num_bytes_reserved) {
                break;
            }
```

**Comment by Safihre** [comment]
I did think of that case 💯
