### ISSUE TITLE
5.4.2 - Could not get filename or CRC value

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabyenc#62]
had a user on discord complain about stuck download, eventually saw too many directunpacker threads
```
2022-08-10 02:31:38,423::INFO::[SABnzbd:423] SABYenc module (v5.4.2)... found!
2022-08-10 02:31:38,425::INFO::[SABnzbd:424] SABYenc module is using SIMD set: AVX
2022-08-10 02:31:38,426::INFO::[SABnzbd:443] Cryptography module (v37.0.2)... found!
2022-08-10 02:31:38,428::INFO::[SABnzbd:448] par2 binary... found (/usr/bin/par2)
2022-08-10 02:31:38,430::INFO::[SABnzbd:455] UNRAR binary... found (/usr/bin/unrar)
2022-08-10 02:31:38,432::INFO::[SABnzbd:463] UNRAR binary version 6.02
2022-08-10 02:31:38,434::INFO::[SABnzbd:471] 7za binary... found (/usr/bin/7za)

2022-08-10 02:31:38,563::INFO::[SABnzbd:1474] Starting SABnzbd.py-3.6.0
...
```

looking earlier I see:
```
2022-08-10 11:58:25,098::INFO::[decoder:263] CRC Error in 1464449655.49123.19@reader.usenetbucket.com
2022-08-10 11:58:31,989::INFO::[decoder:263] CRC Error in 1464449655.49123.19@reader.usenetbucket.com

2022-08-10 11:59:58,208::INFO::[decoder:219] Badly formed yEnc article in 1412323785.18880.57@charlie.bit.my.finger
Traceback (most recent call last):
  File "/app/sabnzbd/decoder.py", line 153, in run
    decoded_data = decode_yenc(article, raw_data)
  File "/app/sabnzbd/decoder.py", line 243, in decode_yenc
    decoded_data, yenc_filename, crc_correct = sabyenc3.decode_usenet_chunks(raw_data)
ValueError: Could not get filename or CRC value

2022-08-10 12:00:55,776::INFO::[decoder:263] CRC Error in 1464449730.51718.6@reader.usenetbucket.com
```

dunno if that messes up anything but just to note in case we need to handle that more gracefully

**Comment by Safihre** [comment]
It's like that on purpose, for debugging of sabyenc. Although, by now we know pretty sure that it's usually a problem with the upload.
But, we've also seen a case where this indicated bad memory module of the user.. So worth to keep that in mind.

**Comment by thezoggy** [comment]
why not just log the error more gracefully rather than let it traceback in the log?
